"""Shared Replicate character-sprite generation logic, used both by the
one-off CLI (scripts/generate_character.py, for pre-warming/testing a full
outfit's pose sheet by hand) and automatically by the pipeline itself
(ensure_outfit_sprites, called from pipeline/visuals.py) to generate on
demand just the poses a given video's script actually needs, in whatever
outfit that video calls for.

Sprites are cached on disk under assets/character/<outfit>/<pose>.png --
once a given (outfit, pose) combination has been generated once, it's
reused for free by every future video that needs it again, so cost only
recurs for genuinely new outfit/pose combinations, not every video. These
are committed to the repo (see .github/workflows/publish.yml's commit step)
so the cache persists across scheduled CI runs too, not just a local
machine.

The character's face, head, and body silhouette never change -- every
generation call for a given outfit is conditioned on that outfit's own
reference image (assets/character/<outfit>/_reference.png, re-derived as a
base64 data URI from the local file each time, so it never depends on a
Replicate delivery URL staying alive) -- only the outfit description and
pose/expression change."""
import math
import os
import time
from pathlib import Path

from PIL import Image, ImageDraw

from . import cost_tracker
from .replicate_gen_utils import (
    THROTTLE_SECONDS,
    download_image,
    image_to_data_uri,
    post_prediction,
    remove_background_via_flood,
    slice_grid_cells,
)
from .utils import DRY_RUN, log

ROOT = Path(__file__).resolve().parent.parent
CHARACTER_DIR = ROOT / "assets" / "character"
# Dry-run placeholder sprites go here instead of CHARACTER_DIR -- writing them into
# the real cache would permanently poison it with throwaway stick-figure placeholders
# that ensure_outfit_sprites would then treat as "already generated" forever after.
DRYRUN_CHARACTER_DIR = ROOT / "assets" / "_dryrun_character"

MODEL = "openai/gpt-image-2.5-flare"

# gpt-image-2.5-flare supports quality tiers low/medium/high/xhigh/max -- "high" is
# priced for photorealistic detail this flat graphic/line-art style doesn't need. "low"
# costs roughly a fifth to a sixth as much (per Replicate's own tier pricing) and still
# renders this simple style cleanly; bump to "medium" if a render ever looks rough.
QUALITY = "low"

BASE_STYLE = (
    "A simple graphic character for a hand-drawn explainer video, whiteboard-animation "
    "style. Off-white circular head, bald with no hair (unless the outfit below "
    "specifically calls for headwear), with soft flat shading, thin expressive dark "
    "eyebrows, simple eyes, and a small expressive mouth -- a friendly, confident face, "
    "not blank or featureless. No glasses unless the outfit below specifically calls for "
    "them. The body is a solid black flat silhouette: a tapered wedge-shaped torso "
    "narrowing at the neck, thin uniform black line arms and legs, no visible hand or "
    "foot detail -- this black silhouette is the character's core identity and must "
    "remain visible as the body, never replaced by separately drawn, fully illustrated "
    "realistic clothing. Any outfit described below is a small accent layered on top of "
    "the silhouette (trim, a collar line, a held prop), not a redrawn garment. No color "
    "besides the character's outfit accents, which may include small muted or gold "
    "details. Clean, minimal, consistent line weight throughout."
)
# Note: the two "no hair / no glasses / outfit is an accent, not a redrawn garment"
# sentences above are a narrow, deliberate re-addition on top of the otherwise-reverted
# wording (see OUTFITS below) -- without them, the "financial"/"business" outfits
# previously caused the model to grow unwanted hair and glasses and draw a fully
# illustrated suit that replaced the black silhouette entirely, breaking character
# identity. This channel runs unattended (new outfits get generated by CI with no human
# review of the result), so this guard stays even though the rest of BASE_STYLE/OUTFITS
# was rolled back to the original wording per request.

# Per-video outfit variants -- script_writer.py picks one of these keys per video based
# on the topic/era. The face/head/body silhouette never changes; only this description
# does, and it's baked into every pose generated for that outfit.
OUTFITS = {
    "standard": "wearing no distinct outfit -- just the plain black silhouette body, no added clothing details",
    "historical": "wearing a draped Roman-style toga with a gold trim edge, and a gold laurel wreath on the head",
    "business": "wearing a black business suit with a thin tie",
    "casual": "wearing a black hoodie",
    "modern": "wearing a black hoodie and small sunglasses",
    "financial": "wearing a black suit and small glasses, holding a tablet under one arm",
}

# Appended to every generation call (reference, single pose, and grid sheet alike) as a
# hard lock against the model gradually redesigning the character over many calls.
CONSISTENCY_SUFFIX = (
    "Character consistency is critical: do not redesign or reinterpret the character. "
    "Preserve the exact same head, facial features, body proportions, outfit, and "
    "line-art style."
)

REFERENCE_PROMPT_TEMPLATE = (
    BASE_STYLE + " The character is {outfit}. Standing in a relaxed, neutral pose, "
    "facing forward, friendly normal expression, full body visible, centered in frame "
    "with margin on all sides, plain white background. " + CONSISTENCY_SUFFIX
)

POSE_PROMPT_TEMPLATE = (
    "Redraw this exact same character -- same head shape and size, same face style, "
    "same outfit, same proportions, same art style -- but change the pose and "
    "expression to: {pose_description}. Keep the exact same line weight and style as "
    "the reference image. Full body visible, centered in frame with margin on all "
    "sides, transparent background. " + CONSISTENCY_SUFFIX
)

# Batched grid-sheet generation for the "long tail" pose set (see pose_descriptions.py's
# CORE_POSES) -- several poses in one image, ~4-8x cheaper per pose than POSE_PROMPT_TEMPLATE
# but lower per-pose resolution after slicing, so reserved for poses that don't get heavy
# screen time. background is requested "opaque" (a multi-figure sheet is more reliable that
# way) and sliced/background-removed locally afterward -- see generate_pose_grid.
GRID_PROMPT_TEMPLATE = (
    BASE_STYLE + " The character is {outfit}.\n\n"
    "Create a grid of {n} separate full-body poses of this SAME character, arranged in "
    "{rows} row(s) of {cols}, in this exact left-to-right, top-to-bottom order, each "
    "pose clearly separated with generous white space between cells and no overlapping "
    "figures:\n{numbered_list}\n\n"
    "Keep all props extremely simple and graphic, matching the whiteboard-animation "
    "aesthetic. Plain white background. " + CONSISTENCY_SUFFIX
)

GRID_BATCH_SIZE = 8  # max poses per grid-sheet call
GRID_COLS = 4


def outfit_dir(outfit: str) -> Path:
    base = DRYRUN_CHARACTER_DIR if DRY_RUN else CHARACTER_DIR
    return base / outfit


def generate_reference(outfit: str, token: str, quality: str = QUALITY, run_id: str = "unknown") -> Path:
    log(f"Generating character reference (outfit={outfit}, quality={quality})...")
    prompt = REFERENCE_PROMPT_TEMPLATE.format(outfit=OUTFITS[outfit])
    data = post_prediction(
        {"prompt": prompt, "aspect_ratio": "1:1", "quality": quality, "background": "opaque"},
        token,
    )
    url = data["output"][0] if isinstance(data["output"], list) else data["output"]
    img = download_image(url)
    out_dir = outfit_dir(outfit)
    out_dir.mkdir(parents=True, exist_ok=True)
    ref_path = out_dir / "_reference.png"
    img.convert("RGB").save(ref_path)
    log(f"  saved {ref_path}")
    cost_tracker.record_replicate_character_call(run_id, outfit, "reference", ["_reference"], quality)
    return ref_path


def generate_pose(outfit: str, pose_name: str, description: str, reference_image: str,
                   token: str, quality: str = QUALITY, run_id: str = "unknown") -> Path:
    log(f"Generating pose '{pose_name}' for outfit '{outfit}' (quality={quality})...")
    prompt = POSE_PROMPT_TEMPLATE.format(pose_description=description)
    data = post_prediction(
        {
            "prompt": prompt,
            "input_images": [reference_image],
            "aspect_ratio": "1:1",
            "quality": quality,
            "background": "transparent",
        },
        token,
    )
    url = data["output"][0] if isinstance(data["output"], list) else data["output"]
    img = download_image(url)
    out_dir = outfit_dir(outfit)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{pose_name}.png"
    img.convert("RGBA").save(out_path)
    log(f"  saved {out_path}")
    cost_tracker.record_replicate_character_call(run_id, outfit, "pose", [pose_name], quality)
    return out_path


def generate_pose_grid(outfit: str, pose_names: list, reference_image: str, token: str,
                        quality: str = QUALITY, cols: int = GRID_COLS, run_id: str = "unknown") -> list:
    """Generates several "long tail" poses in ONE image (a grid sheet) instead of one
    call each -- roughly 4-8x cheaper per pose, at some cost in per-pose sharpness
    after upscaling (each cell is much smaller than a full single-pose generation).
    Slices the result into the same per-pose cached PNG files single-pose generation
    produces, so nothing downstream needs to know which path a given sprite came
    from."""
    from .stickman.pose_descriptions import POSE_DESCRIPTIONS
    n = len(pose_names)
    if n == 0:
        return []
    cols = max(1, min(cols, n))
    rows = math.ceil(n / cols)
    numbered_list = "\n".join(f"{i + 1}. {POSE_DESCRIPTIONS[name]}" for i, name in enumerate(pose_names))
    prompt = GRID_PROMPT_TEMPLATE.format(
        outfit=OUTFITS[outfit], n=n, rows=rows, cols=cols, numbered_list=numbered_list,
    )
    log(f"Generating pose grid for outfit '{outfit}' ({rows}x{cols}): {pose_names}")
    data = post_prediction(
        {
            "prompt": prompt,
            "input_images": [reference_image],
            "aspect_ratio": "1:1",
            "quality": quality,
            "background": "opaque",
        },
        token,
    )
    url = data["output"][0] if isinstance(data["output"], list) else data["output"]
    sheet = download_image(url).convert("RGB")
    out_dir = outfit_dir(outfit)
    out_dir.mkdir(parents=True, exist_ok=True)
    sheet.save(out_dir / f"_grid_debug_{pose_names[0]}.png")  # for manual inspection if slicing looks off
    cost_tracker.record_replicate_character_call(run_id, outfit, f"grid ({rows}x{cols})", pose_names, quality)

    boxes = slice_grid_cells(sheet, n)
    if len(boxes) != n:
        log(f"  Warning: detected {len(boxes)} grid cells but expected {n} -- slicing may be off")
    saved = []
    for i, (name, box) in enumerate(zip(pose_names, boxes)):
        cell = sheet.crop(box)
        cleaned = remove_background_via_flood(cell)
        bbox = cleaned.getbbox()
        if bbox:
            cleaned = cleaned.crop(bbox)
        out_path = out_dir / f"{name}.png"
        cleaned.save(out_path)
        log(f"  saved {out_path} (grid cell {i + 1}/{n})")
        saved.append(out_path)
    return saved


def _placeholder_sprite(pose_name: str) -> Image.Image:
    """Trivial transparent placeholder used only in --dry-run, so the pipeline
    stays fully offline and free when testing (no Replicate calls)."""
    img = Image.new("RGBA", (400, 400), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    draw.ellipse((150, 20, 250, 120), outline=(0, 0, 0, 255), width=4)
    draw.line((200, 120, 200, 280), fill=(0, 0, 0, 255), width=4)
    draw.line((200, 160, 130, 220), fill=(0, 0, 0, 255), width=4)
    draw.line((200, 160, 270, 220), fill=(0, 0, 0, 255), width=4)
    draw.line((200, 280, 140, 380), fill=(0, 0, 0, 255), width=4)
    draw.line((200, 280, 260, 380), fill=(0, 0, 0, 255), width=4)
    draw.text((155, 135), pose_name[:12], fill=(0, 0, 0, 255))
    return img


def ensure_outfit_sprites(outfit: str, pose_names, token: str = None, quality: str = QUALITY,
                           run_id: str = "unknown") -> Path:
    """Makes sure assets/character/<outfit>/<pose>.png exists for every name in
    pose_names, generating (and caching to disk) only whatever's actually
    missing. Returns the outfit's sprite directory."""
    if outfit not in OUTFITS:
        log(f"Warning: unknown outfit '{outfit}', falling back to 'standard'")
        outfit = "standard"

    out_dir = outfit_dir(outfit)
    out_dir.mkdir(parents=True, exist_ok=True)
    pose_names = sorted(set(pose_names) | {"stand", "celebrate"})
    missing = [p for p in pose_names if not (out_dir / f"{p}.png").exists()]

    if not missing:
        log(f"All needed poses already cached for outfit '{outfit}': {pose_names}")
        return out_dir

    if DRY_RUN:
        log(f"Generating placeholder sprites for outfit '{outfit}': {missing} (dry-run, no API call)")
        for pose_name in missing:
            _placeholder_sprite(pose_name).save(out_dir / f"{pose_name}.png")
        return out_dir

    log(f"Outfit '{outfit}' needs {len(missing)} new pose(s): {missing} (rest already cached)")
    token = token or os.environ.get("REPLICATE_API_TOKEN")
    if not token:
        raise RuntimeError("REPLICATE_API_TOKEN is required to generate character sprites")

    ref_path = out_dir / "_reference.png"
    if not ref_path.exists():
        ref_path = generate_reference(outfit, token, quality=quality, run_id=run_id)
        time.sleep(THROTTLE_SECONDS)
    reference_image = image_to_data_uri(ref_path)

    from .stickman.pose_descriptions import CORE_POSES, POSE_DESCRIPTIONS
    unknown = [p for p in missing if p not in POSE_DESCRIPTIONS]
    for p in unknown:
        log(f"Warning: no description for pose '{p}', skipping")
    missing = [p for p in missing if p in POSE_DESCRIPTIONS]
    core_missing = [p for p in missing if p in CORE_POSES]
    long_tail_missing = [p for p in missing if p not in CORE_POSES]

    for pose_name in core_missing:
        generate_pose(outfit, pose_name, POSE_DESCRIPTIONS[pose_name], reference_image, token,
                       quality=quality, run_id=run_id)
        time.sleep(THROTTLE_SECONDS)

    for i in range(0, len(long_tail_missing), GRID_BATCH_SIZE):
        batch = long_tail_missing[i:i + GRID_BATCH_SIZE]
        generate_pose_grid(outfit, batch, reference_image, token, quality=quality, run_id=run_id)
        time.sleep(THROTTLE_SECONDS)

    return out_dir
